var a = "Str";
var b = 5;
var c = undefined;
var d = {};
var e = null;
console.log(a+b);
console.log(a+c);
console.log(a+d);
console.log(a+e);
console.log(a-b);
console.log(a-c);
console.log(a-d);
console.log(a-e);
console.log(a*b);
console.log(a*c);
console.log(a*d);
console.log(a*e);
console.log(a/b);
console.log(a/c);
console.log(a/d);
console.log(a/e);
console.log(+a);
console.log(+b);
console.log(+c);
console.log(+d);
console.log(+e);
console.log(String(b));
console.log(String(c));
console.log(String(d));
console.log(String(e));
console.log(!!a);
console.log(!!b);
console.log(!!c);
console.log(!!d);
console.log(!!e);

